disabled_rules:
  - type_name
  - trailing_whitespace # コードの記載のない改行を許可
  - nesting # ネストを許可
  - multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
  - empty_enum_arguments # enumの引数を省略したいため

included:
  - ${PWD}/githubSearchAPISample

excluded:
  - ${PWD}/Pods
  - ${PWD}/githubSearchAPISampleTests
  - ${PWD}/githubSearchAPISampleUITests

# 1行の文字列制限
line_length:
  - 200   # warning
  - 300   # error

# 型の行数制限
type_body_length:
  - 400   # warning
  - 600   # error

# 1ファイルの行数制限
file_length:
  - 500   # warning
  - 1000  # error

# メソッドの行数制限
function_body_length:
  - 100   # warning
  - 200   # error

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - x
    - y
    - vc
    - on

reporter: "xcode"
